
version: "3"
services:
    www:
        image: php:7.2-apache
        ports:
            - "80:80"
        volumes:
            - ./wwwexternal:/var/www/html
        container_name: web_server
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
        networks:
            - default
        container_name: mysql_server
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
        container_name: phpmyadmin_server
